name: Auto publish API specification to exchange using Autocatalog CLI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Catalog-CLI
      run: |
        sudo apt-get update
        npm install -g api-catalog-cli@latest
    - name: Create Descriptor file
      run: |   
        api-catalog create-descriptor -d catalog.yaml
    - name: Publish to Exchange
      env:
        PLATFORM_ORGID: ${{secrets.PLATFORM_ORGID}}
        PLATFORM_USERNAME: ${{secrets.PLATFORM_USERNAME}}
        PLATFORM_PASSWORD: ${{secrets.PLATFORM_PASSWORD}}
      run: |
          api-catalog publish-asset --organization="$PLATFORM_ORGID" --username="$PLATFORM_USERNAME" --password="$PLATFORM_PASSWORD" --trigger-criteria=branches:main  --version-strategy-criteria= branches:main 
    

 
